#!/usr/bin/env bash
# Transfering a file from our client device to a server:
# Takes 4 parameters:
## 4: Path to SSH private key that is required for scp
## 1: Path to the file that will be transferred
## 3: Username that scp connects with
## 2: IP of the server that we want to transfer the file to

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi