#!/usr/bin/env bash
# Installsing Nginx with the following configurations:
## Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

# listen on port 80 not 80 default
sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default

/etc/init.d/nginx restart
