#!/usr/bin/env bash
# Installsing Nginx with the following configurations:
## Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;

    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default

service nginx restart