#!/usr/bin/env bash
# Looping from 1 to 10, then printing:
#   "bad luck" for the 4th time
#   "good luck" for the 8th time
#   "Best School" for other times

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
