#!/usr/bin/env bash
# Printing the time for 12 hours and 59 minutes.
#   Printing hours from 0 to 12
#   Printing minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  mins=1
  while [ $mins -le 59 ]
  do
    echo "$mins"
    (( mins++ ))
  done
  (( hour++ ))
done
